export const SUBJECT_SEED = [
  { name: "Quantitative Aptitude", slug: "quantitative-aptitude", displayOrder: 1 },
  {
    name: "General Intelligence & Reasoning",
    slug: "general-intelligence-reasoning",
    displayOrder: 2,
  },
  { name: "English Comprehension", slug: "english-comprehension", displayOrder: 3 },
  { name: "General Awareness", slug: "general-awareness", displayOrder: 4 },
] as const;

export type TopicSeedItem = {
  name: string;
  section?: string;
  status?: "not_started" | "in_progress" | "done";
  confidence?: number;
};

function sectionTopics(section: string, names: string[]): TopicSeedItem[] {
  return names.map((name) => ({ name, section }));
}

/**
 * Old topic names → new names, so existing progress/MCQs stay attached when
 * the syllabus is refined.
 */
export const TOPIC_RENAMES_BY_SLUG: Record<string, Record<string, string>> = {
  "quantitative-aptitude": {
    "Profit and Loss": "Profit, Loss & Discount",
    "Ratio and Proportion": "Ratio & Proportion",
    Geometry: "Plane Geometry",
    Mensuration: "Mensuration 2D",
    "Time Speed and Distance": "Time and Distance",
    "Mixture and Alligation": "Weighted Average & Alligation",
  },
  "general-intelligence-reasoning": {
    Analogy: "Analogy & Similarity",
    "Series (Number/Alphabet)": "Number & Letter Series",
    "Coding-Decoding": "Coding Decoding",
    "Blood Relations": "Blood Relation",
    "Direction Sense": "Direction Test",
    "Ranking and Order": "Order & Ranking",
    "Venn Diagrams": "Venn Diagram",
    "Non-Verbal Reasoning": "Non Verbal Series",
    "Statement and Conclusion": "Statement & Conclusion",
  },
};

/** @deprecated use TOPIC_RENAMES_BY_SLUG */
export const QUANT_TOPIC_RENAMES =
  TOPIC_RENAMES_BY_SLUG["quantitative-aptitude"];

export const TOPIC_SEED: Record<string, TopicSeedItem[]> = {
  "quantitative-aptitude": [
    { name: "Number System" },
    { name: "HCF and LCM" },
    { name: "Percentage" },
    { name: "Simple Interest" },
    { name: "Compound Interest" },
    { name: "Installments" },
    { name: "Profit, Loss & Discount" },
    { name: "Ratio & Proportion" },
    { name: "Partnership" },
    { name: "Average" },
    { name: "Weighted Average & Alligation" },
    { name: "Time and Work" },
    { name: "Time and Distance" },
    { name: "Data Interpretation" },
    { name: "Algebra" },
    { name: "Equations" },
    { name: "AP, GP, HP" },
    { name: "Surds & Indices" },
    { name: "Simplification" },
    { name: "Plane Geometry" },
    { name: "Mass Plane Geometry" },
    { name: "Mensuration 2D" },
    { name: "Mensuration 3D" },
    { name: "Trigonometry" },
    { name: "Height and Distance" },
    { name: "Coordinate Geometry" },
    { name: "Statistics" },
    { name: "Permutation & Combination" },
    { name: "Probability" },
  ],
  "general-intelligence-reasoning": [
    { name: "Alphabet Test" },
    { name: "Coding Decoding" },
    { name: "Number & Letter Series" },
    { name: "Alphanumeric Series" },
    { name: "Analogy & Similarity" },
    { name: "Classification" },
    { name: "Direction Test" },
    { name: "Blood Relation" },
    { name: "Order & Ranking" },
    { name: "Seating Arrangement" },
    { name: "Puzzle" },
    { name: "Syllogism" },
    { name: "Inequalities" },
    { name: "Calendar" },
    { name: "Clock" },
    { name: "Data Sufficiency" },
    { name: "Word Formation" },
    { name: "Logical Sequence of Words" },
    { name: "Venn Diagram" },
    { name: "Mathematical Operations" },
    { name: "Arithmetical Reasoning" },
    { name: "Input Output" },
    { name: "Character Puzzle" },
    { name: "Matrix" },
    { name: "Course of Action" },
    { name: "Statement & Assumption" },
    { name: "Statement & Arguments" },
    { name: "Cause & Effect" },
    { name: "Counting of Figures" },
    { name: "Dice" },
    { name: "Cube & Cuboid" },
    { name: "Mirror/Water Image" },
    { name: "Paper Cutting & Folding" },
    { name: "Embedded Figures" },
    { name: "Image Analysis" },
    { name: "Group of Identical Figures" },
    { name: "Incomplete Figures" },
    { name: "Dot Situation" },
    { name: "Non Verbal Series" },
    { name: "Non Verbal Analogy" },
    { name: "Non Verbal Classification" },
    { name: "Statement & Conclusion" },
    { name: "Statement & Inferences" },
  ],
  "english-comprehension": [
    { name: "Reading Comprehension" },
    { name: "Cloze Test" },
    { name: "Error Spotting" },
    { name: "Sentence Improvement" },
    { name: "Fill in the Blanks" },
    { name: "Synonyms/Antonyms" },
    { name: "Idioms and Phrases" },
    { name: "One Word Substitution" },
    { name: "Spelling Correction" },
    { name: "Para Jumbles" },
    { name: "Active-Passive Voice" },
    { name: "Direct-Indirect Speech" },
  ],
  "general-awareness": [
    ...sectionTopics("Geography", [
      "Solar System",
      "Longitude and Latitude",
      "Earth's Interior and Plate Tectonics",
      "Rocks, Continents, and Oceans",
      "Geomorphology",
      "Landforms",
      "Atmosphere",
      "Wind, Ocean Current, and Cyclone",
      "India and Its Location",
      "Himalayas",
      "Peninsular Plateau",
      "Northern Plains and Islands",
      "Himalayan River System",
      "Peninsular Rivers",
      "Dams, Lakes and Waterfall",
      "Monsoon",
      "Forest and Grassland",
      "Soil",
      "Agriculture",
      "Minerals",
      "World Map",
      "Human Geography",
      "Transport",
    ]),
    ...sectionTopics("Ancient History", [
      "Stone Age",
      "Indus Valley Civilization",
      "Vedic Age",
      "Sangam Age",
      "Jainism and Buddhism",
      "Mahajanapadas",
      "Maurya Dynasty",
      "Post-Maurya Dynasties",
      "Gupta Dynasty",
      "Post-Gupta Dynasties",
      "Tripartite Struggle and Cholas",
    ]),
    ...sectionTopics("Medieval History", [
      "Delhi Sultanate",
      "Vijayanagara and Bahmani Kingdom",
      "The Mughal Empire",
      "Marathas",
      "Bhakti and Sufi Movements",
    ]),
    ...sectionTopics("Modern History", [
      "Advent of Europeans",
      "Socio Religious Reforms",
      "Revolt of 1857",
      "Indian National Congress",
      "Bengal Partition",
      "Gandhian Era",
      "CDM and Simon Commission",
      "Quit India Movement",
      "Governor-General and Viceroy",
    ]),
    ...sectionTopics("Polity", [
      "Making of Constitution",
      "Salient Features of the Constitution",
      "Preamble",
      "Part 1 and Part 2 of the Constitution",
      "Fundamental Rights",
      "DPSP and Fundamental Duties",
      "President and Vice President of India",
      "Prime Minister and Council of Ministers",
      "Parliament",
      "State Legislature",
      "Centre-State Relations",
      "Emergency and Constitutional Amendment",
      "Supreme Court and High Court",
      "Local Government",
      "Constitutional and Non-Constitutional Bodies",
      "New Criminal Laws 2023",
      "Important Acts",
      "Sources of the Indian Constitution",
      "Noteworthy Points",
    ]),
    ...sectionTopics("Economics", [
      "Basics of Economy",
      "Microeconomics",
      "National Income",
      "Budget and Taxation",
      "Inflation and Unemployment",
      "Banking: Part 1",
      "Monetary Policy",
      "Banking: Part 2",
      "Poverty and Balance of Payment",
      "Five Year Plan and Industrial Policy Resolution",
      "Indices, Reports, International Institutions and Key Economic Concepts",
    ]),
    ...sectionTopics("Physics", [
      "Motion",
      "Force and Laws of Motion",
      "Gravitation and Work Done",
      "Sound",
      "Reflection and Refraction",
      "Human Eye and Vision",
      "Electricity",
      "Magnetic Effect of Electric Current",
    ]),
    ...sectionTopics("Chemistry", [
      "Matter",
      "Atom and Its Structure",
      "Periodic Table",
      "Chemical Reactions",
      "Metals and Non-Metals",
      "Acid, Base and Salt",
      "Carbon and Its Compounds",
    ]),
    ...sectionTopics("Biology", [
      "Cell",
      "Plant Tissue and Animal Tissue",
      "Plant and Animal Kingdom",
      "Nervous System",
      "Hormones and Plant Movement",
      "Reproduction",
      "Digestion and Respiration",
      "Circulatory System and Excretory System",
      "Diseases",
      "Nutrients",
      "Heredity and Evolution",
    ]),
    ...sectionTopics("Environment", [
      "Basics of Environmental Sciences",
      "Ecosystem",
      "Trophic Dynamics and Energy Transfer",
      "Biogeochemical Cycles",
      "Environmental Conventions",
      "National Parks",
    ]),
    ...sectionTopics("Static GK", [
      "Music and Paintings",
      "Classical Dance",
      "Folk Dances of India",
      "Festivals of India",
      "Census",
      "Important Days",
      "Books and Authors",
      "Sports",
      "International Organisations",
      "National Organisations",
      "Awards and Honours",
    ]),
  ],
};

/**
 * First-pass study time per topic, in minutes. Quant hours come from a
 * question-volume-based plan (estimated hours in the source CSV); other
 * subjects stay on the earlier research-based defaults.
 */
const SUBJECT_DEFAULT_MINUTES: Record<string, number> = {
  "quantitative-aptitude": 600,
  "general-intelligence-reasoning": 150,
  "english-comprehension": 210,
  "general-awareness": 30,
};

/** GA varies a lot by block — Polity and Modern History are the dense ones. */
const GA_SECTION_MINUTES: Record<string, number> = {
  Geography: 30,
  "Ancient History": 30,
  "Medieval History": 30,
  "Modern History": 45,
  Polity: 45,
  Economics: 35,
  Physics: 30,
  Chemistry: 30,
  Biology: 30,
  Environment: 20,
  "Static GK": 20,
};

/** Hours → minutes, rounded. Source: Quant topic plan with estimated_hours. */
function hoursToMinutes(hours: number) {
  return Math.max(5, Math.round(hours * 60));
}

const TOPIC_MINUTE_OVERRIDES: Record<string, number> = {
  // Quant — from estimated_hours in the syllabus plan
  "Number System": hoursToMinutes(34.76),
  "HCF and LCM": hoursToMinutes(7.57),
  Percentage: hoursToMinutes(17.49),
  "Simple Interest": hoursToMinutes(4.08),
  "Compound Interest": hoursToMinutes(7.88),
  Installments: hoursToMinutes(3.83),
  "Profit, Loss & Discount": hoursToMinutes(16.55),
  "Ratio & Proportion": hoursToMinutes(9.6),
  Partnership: hoursToMinutes(2.93),
  Average: hoursToMinutes(11.39),
  "Weighted Average & Alligation": hoursToMinutes(7.67),
  "Time and Work": hoursToMinutes(9.55),
  "Time and Distance": hoursToMinutes(15.32),
  "Data Interpretation": hoursToMinutes(10.32),
  Algebra: hoursToMinutes(31.92),
  Equations: hoursToMinutes(10.66),
  "AP, GP, HP": hoursToMinutes(3.4),
  "Surds & Indices": hoursToMinutes(8.36),
  Simplification: hoursToMinutes(4.98),
  "Plane Geometry": hoursToMinutes(50.15),
  "Mass Plane Geometry": hoursToMinutes(0.98),
  "Mensuration 2D": hoursToMinutes(26.68),
  "Mensuration 3D": hoursToMinutes(24.14),
  Trigonometry: hoursToMinutes(24.84),
  "Height and Distance": hoursToMinutes(5.18),
  "Coordinate Geometry": hoursToMinutes(11.86),
  Statistics: hoursToMinutes(4.65),
  "Permutation & Combination": hoursToMinutes(8.7),
  Probability: hoursToMinutes(9.6),
  // Reasoning — puzzles / seating / non-verbal need more drill time
  "Alphabet Test": 90,
  "Coding Decoding": 180,
  "Number & Letter Series": 180,
  "Alphanumeric Series": 150,
  "Analogy & Similarity": 120,
  Classification: 120,
  "Direction Test": 120,
  "Blood Relation": 150,
  "Order & Ranking": 150,
  "Seating Arrangement": 300,
  Puzzle: 360,
  Syllogism: 180,
  Inequalities: 150,
  Calendar: 90,
  Clock: 90,
  "Data Sufficiency": 180,
  "Word Formation": 90,
  "Logical Sequence of Words": 90,
  "Venn Diagram": 120,
  "Mathematical Operations": 120,
  "Arithmetical Reasoning": 150,
  "Input Output": 240,
  "Character Puzzle": 120,
  Matrix: 90,
  "Course of Action": 120,
  "Statement & Assumption": 120,
  "Statement & Arguments": 120,
  "Cause & Effect": 120,
  "Counting of Figures": 150,
  Dice: 120,
  "Cube & Cuboid": 150,
  "Mirror/Water Image": 120,
  "Paper Cutting & Folding": 150,
  "Embedded Figures": 120,
  "Image Analysis": 120,
  "Group of Identical Figures": 90,
  "Incomplete Figures": 120,
  "Dot Situation": 90,
  "Non Verbal Series": 180,
  "Non Verbal Analogy": 150,
  "Non Verbal Classification": 150,
  "Statement & Conclusion": 120,
  "Statement & Inferences": 120,
  // English — vocabulary is a long grind, mechanics are quick
  "Reading Comprehension": 300,
  "Error Spotting": 300,
  "Synonyms/Antonyms": 300,
  "Idioms and Phrases": 240,
  "One Word Substitution": 240,
  "Sentence Improvement": 240,
  "Spelling Correction": 120,
  "Fill in the Blanks": 150,
  "Active-Passive Voice": 150,
  "Direct-Indirect Speech": 150,
  // GA — the few blocks that genuinely take a sitting
  "Indian Constitution": 60,
  "Fundamental Rights": 60,
  "Revolt of 1857": 45,
};

/** Estimated first-pass minutes for a seeded topic. */
export function seedEstimateMinutes(
  subjectSlug: string,
  topic: TopicSeedItem
): number {
  const override = TOPIC_MINUTE_OVERRIDES[topic.name];
  if (override) return override;

  if (topic.section && GA_SECTION_MINUTES[topic.section]) {
    return GA_SECTION_MINUTES[topic.section];
  }

  return SUBJECT_DEFAULT_MINUTES[subjectSlug] ?? 60;
}

/** Canonical GA section order for progress UI. */
export const GA_SECTION_ORDER = [
  "Geography",
  "Ancient History",
  "Medieval History",
  "Modern History",
  "Polity",
  "Economics",
  "Physics",
  "Chemistry",
  "Biology",
  "Environment",
  "Static GK",
] as const;
