export const SUBJECT_SEED = [
  { name: "Quantitative Aptitude", slug: "quantitative-aptitude", displayOrder: 1 },
  {
    name: "General Intelligence & Reasoning",
    slug: "general-intelligence-reasoning",
    displayOrder: 2,
  },
  { name: "English Comprehension", slug: "english-comprehension", displayOrder: 3 },
  { name: "General Awareness", slug: "general-awareness", displayOrder: 4 },
] as const;

export const TOPIC_SEED: Record<
  string,
  { name: string; status?: "not_started" | "in_progress" | "done"; confidence?: number }[]
> = {
  "quantitative-aptitude": [
    { name: "Percentage", status: "in_progress", confidence: 2 },
    { name: "Profit and Loss", status: "in_progress", confidence: 2 },
    { name: "Simple Interest", status: "in_progress", confidence: 2 },
    { name: "Compound Interest", status: "in_progress", confidence: 2 },
    { name: "Ratio and Proportion", status: "in_progress", confidence: 2 },
    { name: "Average" },
    { name: "Number System" },
    { name: "HCF and LCM" },
    { name: "Algebra" },
    { name: "Geometry" },
    { name: "Mensuration" },
    { name: "Trigonometry" },
    { name: "Time Speed and Distance" },
    { name: "Time and Work" },
    { name: "Data Interpretation" },
    { name: "Mixture and Alligation" },
  ],
  "general-intelligence-reasoning": [
    { name: "Analogy" },
    { name: "Classification" },
    { name: "Series (Number/Alphabet)" },
    { name: "Coding-Decoding" },
    { name: "Blood Relations" },
    { name: "Direction Sense" },
    { name: "Ranking and Order" },
    { name: "Syllogism" },
    { name: "Venn Diagrams" },
    { name: "Non-Verbal Reasoning" },
    { name: "Puzzle" },
    { name: "Matrix" },
    { name: "Word Formation" },
    { name: "Statement and Conclusion" },
  ],
  "english-comprehension": [
    { name: "Reading Comprehension" },
    { name: "Cloze Test" },
    { name: "Error Spotting" },
    { name: "Sentence Improvement" },
    { name: "Fill in the Blanks" },
    { name: "Synonyms/Antonyms" },
    { name: "Idioms and Phrases" },
    { name: "One Word Substitution" },
    { name: "Spelling Correction" },
    { name: "Para Jumbles" },
    { name: "Active-Passive Voice" },
    { name: "Direct-Indirect Speech" },
  ],
  "general-awareness": [
    { name: "History" },
    { name: "Geography" },
    { name: "Indian Polity" },
    { name: "Economics" },
    { name: "Static GK" },
    { name: "Science" },
    { name: "Current Affairs" },
    { name: "Books and Authors" },
    { name: "Awards and Honours" },
    { name: "Important Days" },
  ],
};
