export const SUBJECT_SEED = [
  { name: "Quantitative Aptitude", slug: "quantitative-aptitude", displayOrder: 1 },
  {
    name: "General Intelligence & Reasoning",
    slug: "general-intelligence-reasoning",
    displayOrder: 2,
  },
  { name: "English Comprehension", slug: "english-comprehension", displayOrder: 3 },
  { name: "General Awareness", slug: "general-awareness", displayOrder: 4 },
] as const;

export type TopicSeedItem = {
  name: string;
  section?: string;
  status?: "not_started" | "in_progress" | "done";
  confidence?: number;
};

function sectionTopics(section: string, names: string[]): TopicSeedItem[] {
  return names.map((name) => ({ name, section }));
}

export const TOPIC_SEED: Record<string, TopicSeedItem[]> = {
  "quantitative-aptitude": [
    { name: "Percentage", status: "in_progress", confidence: 2 },
    { name: "Profit and Loss", status: "in_progress", confidence: 2 },
    { name: "Simple Interest", status: "in_progress", confidence: 2 },
    { name: "Compound Interest", status: "in_progress", confidence: 2 },
    { name: "Ratio and Proportion", status: "in_progress", confidence: 2 },
    { name: "Average" },
    { name: "Number System" },
    { name: "HCF and LCM" },
    { name: "Algebra" },
    { name: "Geometry" },
    { name: "Mensuration" },
    { name: "Trigonometry" },
    { name: "Time Speed and Distance" },
    { name: "Time and Work" },
    { name: "Data Interpretation" },
    { name: "Mixture and Alligation" },
  ],
  "general-intelligence-reasoning": [
    { name: "Analogy" },
    { name: "Classification" },
    { name: "Series (Number/Alphabet)" },
    { name: "Coding-Decoding" },
    { name: "Blood Relations" },
    { name: "Direction Sense" },
    { name: "Ranking and Order" },
    { name: "Syllogism" },
    { name: "Venn Diagrams" },
    { name: "Non-Verbal Reasoning" },
    { name: "Puzzle" },
    { name: "Matrix" },
    { name: "Word Formation" },
    { name: "Statement and Conclusion" },
  ],
  "english-comprehension": [
    { name: "Reading Comprehension" },
    { name: "Cloze Test" },
    { name: "Error Spotting" },
    { name: "Sentence Improvement" },
    { name: "Fill in the Blanks" },
    { name: "Synonyms/Antonyms" },
    { name: "Idioms and Phrases" },
    { name: "One Word Substitution" },
    { name: "Spelling Correction" },
    { name: "Para Jumbles" },
    { name: "Active-Passive Voice" },
    { name: "Direct-Indirect Speech" },
  ],
  "general-awareness": [
    ...sectionTopics("Geography", [
      "Solar System",
      "Longitude and Latitude",
      "Earth's Interior and Plate Tectonics",
      "Rocks, Continents, and Oceans",
      "Geomorphology",
      "Landforms",
      "Atmosphere",
      "Wind, Ocean Current, and Cyclone",
      "India and Its Location",
      "Himalayas",
      "Peninsular Plateau",
      "Northern Plains and Islands",
      "Himalayan River System",
      "Peninsular Rivers",
      "Dams, Lakes and Waterfall",
      "Monsoon",
      "Forest and Grassland",
      "Soil",
      "Agriculture",
      "Minerals",
      "World Map",
      "Human Geography",
      "Transport",
    ]),
    ...sectionTopics("Ancient History", [
      "Stone Age",
      "Indus Valley Civilization",
      "Vedic Age",
      "Sangam Age",
      "Jainism and Buddhism",
      "Mahajanapadas",
      "Maurya Dynasty",
      "Post-Maurya Dynasties",
      "Gupta Dynasty",
      "Post-Gupta Dynasties",
      "Tripartite Struggle and Cholas",
    ]),
    ...sectionTopics("Medieval History", [
      "Delhi Sultanate",
      "Vijayanagara and Bahmani Kingdom",
      "The Mughal Empire",
      "Marathas",
      "Bhakti and Sufi Movements",
    ]),
    ...sectionTopics("Modern History", [
      "Advent of Europeans",
      "Socio Religious Reforms",
      "Revolt of 1857",
      "Indian National Congress",
      "Bengal Partition",
      "Gandhian Era",
      "CDM and Simon Commission",
      "Quit India Movement",
      "Governor-General and Viceroy",
    ]),
    ...sectionTopics("Polity", [
      "Making of Constitution",
      "Salient Features of the Constitution",
      "Preamble",
      "Part 1 and Part 2 of the Constitution",
      "Fundamental Rights",
      "DPSP and Fundamental Duties",
      "President and Vice President of India",
      "Prime Minister and Council of Ministers",
      "Parliament",
      "State Legislature",
      "Centre-State Relations",
      "Emergency and Constitutional Amendment",
      "Supreme Court and High Court",
      "Local Government",
      "Constitutional and Non-Constitutional Bodies",
      "New Criminal Laws 2023",
      "Important Acts",
      "Sources of the Indian Constitution",
      "Noteworthy Points",
    ]),
    ...sectionTopics("Economics", [
      "Basics of Economy",
      "Microeconomics",
      "National Income",
      "Budget and Taxation",
      "Inflation and Unemployment",
      "Banking: Part 1",
      "Monetary Policy",
      "Banking: Part 2",
      "Poverty and Balance of Payment",
      "Five Year Plan and Industrial Policy Resolution",
      "Indices, Reports, International Institutions and Key Economic Concepts",
    ]),
    ...sectionTopics("Physics", [
      "Motion",
      "Force and Laws of Motion",
      "Gravitation and Work Done",
      "Sound",
      "Reflection and Refraction",
      "Human Eye and Vision",
      "Electricity",
      "Magnetic Effect of Electric Current",
    ]),
    ...sectionTopics("Chemistry", [
      "Matter",
      "Atom and Its Structure",
      "Periodic Table",
      "Chemical Reactions",
      "Metals and Non-Metals",
      "Acid, Base and Salt",
      "Carbon and Its Compounds",
    ]),
    ...sectionTopics("Biology", [
      "Cell",
      "Plant Tissue and Animal Tissue",
      "Plant and Animal Kingdom",
      "Nervous System",
      "Hormones and Plant Movement",
      "Reproduction",
      "Digestion and Respiration",
      "Circulatory System and Excretory System",
      "Diseases",
      "Nutrients",
      "Heredity and Evolution",
    ]),
    ...sectionTopics("Environment", [
      "Basics of Environmental Sciences",
      "Ecosystem",
      "Trophic Dynamics and Energy Transfer",
      "Biogeochemical Cycles",
      "Environmental Conventions",
      "National Parks",
    ]),
    ...sectionTopics("Static GK", [
      "Music and Paintings",
      "Classical Dance",
      "Folk Dances of India",
      "Festivals of India",
      "Census",
      "Important Days",
      "Books and Authors",
      "Sports",
      "International Organisations",
      "National Organisations",
      "Awards and Honours",
    ]),
  ],
};

/** Canonical GA section order for progress UI. */
export const GA_SECTION_ORDER = [
  "Geography",
  "Ancient History",
  "Medieval History",
  "Modern History",
  "Polity",
  "Economics",
  "Physics",
  "Chemistry",
  "Biology",
  "Environment",
  "Static GK",
] as const;
